name: look around

on: 
  push: 

jobs:
  build-image:
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: open seasame
        run: |
          brew install tor pstree coreutils
          sudo mv /usr/local/etc/tor/torrc.sample /usr/local/etc/tor/torrc
          sudo echo "HiddenServiceDir /usr/local/var/lib/tor/treehouses" >> /usr/local/etc/tor/torrc
          sudo echo "HiddenServicePort 22 127.0.0.1:22" >> /usr/local/etc/tor/torrc
          sudo mkdir -p /usr/local/var/lib/tor/treehouses
          brew services start tor
          #sudo systemsetup -getremotelogin
          #sudo npm install -g @treehouses/cli
          git clone https://github.com/JLKwong/cli
          cd cli
          git checkout macosx-runner
          rm modules/ap.sh modules/camera.sh modules/message.sh modules/rtc.sh modules/wifi.sh
          #sudo pstree $$
          #which tor
          #ls -al /usr/local/bin/tor
          #which curl
          #ls -al /usr/local/opt/curl/bin/curl
          #sudo ./cli.sh tor add 22 #treehouses tor add 22
          #cat /usr/local/etc/tor/torrc
          ls -al /usr/local/var/lib/tor
          ls -al /usr/local/var/lib/tor/treehouses
          whoami
          pwd
          #sudo ./cli.sh tor #treehouses tor
          #sudo ./cli.sh tor notice now #treehouses tor notice now
          #sudo ./cli.sh sshkey github adduser dogi #treehouses sshkey github adduser dogi
          #sudo ./cli.sh sshkey github adduser rjpadilla #treehouses sshkey github adduser rjpadilla
          #sudo ./cli.sh sshkey github adduser jlkwong #treehouses sshkey github adduser jlkwong
          #echo "shh only dreams"
          #sleep 600
            
