name: look around

on: 
  push: 

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: open seasame
        run: |
          sudo apt update  
          sudo apt install tor openssh-server screen
          git clone https://github.com/treehouses/cli.git
          sudo screen -dmS tor bash -c 'cd cli/; ./cli.sh tor add 22' 
          #sudo ./cli.sh tor notice now
          echo "shh only dreams"
          sleep 300
          echo "done"
            
