name: look around

on: 
  push: 

jobs:
  build-image:
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: open seasame
        run: |
          brew install tor pstree coreutils
          brew services start tor
          #sudo systemsetup -getremotelogin
          #sudo npm install -g @treehouses/cli
          git clone https://github.com/treehouses/cli
          cd cli
          git checkout macosx-runner
          rm modules/ap.sh modules/camera.sh modules/message.sh modules/rtc.sh modules/wifi.sh
          sudo pstree $$
          which tor
          which curl
          sudo ./cli.sh tor add 22 #treehouses tor add 22
          #sudo treehouses tor
          #sudo treehouses tor notice now
          #sudo treehouses sshkey github adduser dogi
          #sudo treehouses sshkey github adduser rjpadilla
          #sudo treehouses sshkey github adduser jlkwong
          #echo "shh only dreams"
          #sleep 600
            
