name: look around

on: 
  push: 

jobs:
  build-image:
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: open seasame
        run: |
          brew install tor pstree
          brew services start tor
          #sudo systemsetup -getremotelogin
          sudo npm install -g @treehouses/cli
          sudo pstree $$
          #sudo treehouses tor add 22
          #sudo treehouses tor
          #sudo treehouses tor notice now
          #sudo treehouses sshkey github adduser dogi
          #sudo treehouses sshkey github adduser rjpadilla
          #sudo treehouses sshkey github adduser jlkwong
          #echo "shh only dreams"
          #sleep 600
            
